# This is a basic workflow to help you get started with Actions

name: workflow_run

# Controls when the action will run. 
on:
 workflow_run:
   workflows: [CI]
   branches: [main]
   types:
     - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Get the action status
        run: echo ${{ github.event.action }}

      # Runs a set of commands using the runners shell
      - name: Sender details
        run: echo ${{ github.event.sender.login }}
     
